from building import *

cwd = GetCurrentDir()
src = Glob("*.c")
path = [
    cwd,
    os.path.join(cwd, "..", "include"),
]

group = DefineGroup("Protocol", src, CPPPATH=path, depend=[""])

Return("group")
